name: Build

on:
  workflow_dispatch:
    inputs:
      changesetId:
        description: "changeset Id to tag the container image"
        required: true
  # push:
  #   branches:
  #     - main

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set variables
        id: vars
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@master

      - name: Authenticate to GCP (Securely)
        uses: google-github-actions/auth@v1
        with:
          # token_format: access_token
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}  # Optional, but recommended for clarity

      - name: Authenticate with GCP
        id: auth
        uses: "google-github-actions/auth@v1"
        with:
          token_format: access_token
          credentials_json: ${{ secrets.GCP_JSON_KEY }}
          access_token_lifetime: 300s

      - name: Login into Google Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.GCP_ARTIFACT_REPOSITORY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build & Push docker image for API
        run: |
          docker build -t qtest/second:latest .
          docker tag qtest/second:latest ${{ secrets.GCP_ARTIFACT_REPOSITORY }}/qsecond:latest
          docker tag qtest/second:latest ${{ secrets.GCP_ARTIFACT_REPOSITORY }}/qsecond:${{ steps.vars.outputs.short_sha }}
          docker tag qtest/second:latest ${{ secrets.GCP_ARTIFACT_REPOSITORY }}/qsecond:${{ inputs.changesetId }}
          docker push ${{ secrets.GCP_ARTIFACT_REPOSITORY }}/qsecond:latest
          docker push ${{ secrets.GCP_ARTIFACT_REPOSITORY }}/qsecond:${{ steps.vars.outputs.short_sha }}
          docker push ${{ secrets.GCP_ARTIFACT_REPOSITORY }}/qsecond:${{ inputs.changesetId }}
