name: Deploy to Cloud Run

on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: "Target branch for the workflow"
        required: true
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set variables
        id: vars
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@master

      - name: Authenticate to GCP (Securely)
        uses: google-github-actions/auth@v1
        with:
          # token_format: access_token
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}  # Optional, but recommended for clarity

      - name: Authenticate with GCP
        id: auth
        uses: "google-github-actions/auth@v1"
        with:
          token_format: access_token
          credentials_json: ${{ secrets.GCP_JSON_KEY }}
          access_token_lifetime: 300s

      - name: Login into Google Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.GCP_ARTIFACT_REPOSITORY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      # - name: Set up Google Cloud SDK
      #   uses: google-github-actions/setup-gcloud@master
      #   with:
      #     project_id: ${{ secrets.GCP_PROJECT_ID }}
      #     service_account_key: ${{ secrets.GCP_SA_KEY }}
      #     export_default_credentials: true

      # - name: Configure Docker
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.x'

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push docker image for API
        run: |
          docker build -t qtest/first:latest .
          docker tag qtest/first:latest ${{ secrets.GCP_ARTIFACT_REPOSITORY }}/qsecond:latest
          docker tag qtest/first:latest ${{ secrets.GCP_ARTIFACT_REPOSITORY }}/qsecond:${{ steps.vars.outputs.short_sha }}
          docker push ${{ secrets.GCP_ARTIFACT_REPOSITORY }}/qsecond:latest
          docker push ${{ secrets.GCP_ARTIFACT_REPOSITORY }}/qsecond:${{ steps.vars.outputs.short_sha }}


      # - name: Build Docker image
      #   run: docker build -t qtest1:latest .

      # - name: Tag Docker image
      #   run: docker tag qtest1:latest ${{ secrets.DOCKER_USERNAME }}/qtest1:latest

      # - name: Push Docker image to Docker Hub
      #   run: docker push ${{ secrets.DOCKER_USERNAME }}/qtest1:latest

      # - name: Deploy to Cloud Run
      #   run: gcloud run deploy my-service --image=${{ secrets.DOCKER_USERNAME }}/qtest1:latest --platform=managed --region=us-central1

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Deploy
        run: |
          gcloud run deploy qsecond \
          --region europe-west1 \
          --image ${{ secrets.GCP_ARTIFACT_REPOSITORY }}/qsecond:${{ steps.vars.outputs.short_sha }} \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}
          --port 8080
