name: Multiple Actions on Labeled PR

on:
  pull_request:
    types: labeled  # Trigger on PR labeled
  workflow_dispatch:
    inputs:
      target-branch:
        description: "Target branch for the workflow"
        required: true


jobs:
  job1:
    if: github.event_name == 'pull_request' && github.event.action == 'labeled' && contains(github.event.pull_request.labels.*.name, 'quantm now')
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo action 2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo target branch: ${{ inputs.target-branch }}